import logging
from pydantic import ValidationError
from ..models.state import Plan, Task, ToolCall
from ..llm.client import LLMClient
import json

logger = logging.getLogger(__name__)

PLANNER_PROMPT = """You are a master task planner for an autonomous agent.
Your objective is to decompose the following user goal into a concrete, sequential Plan consisting of individual Tasks.
Ensure that dependencies are correctly mapped using the task_id.
User Goal: {goal}
Return a structured Plan."""

TOOL_CALL_PROMPT = """You are an agent executing a task.
Based on the task description and required tools, determine the correct tool call to make.
Task description: {task_description}
Expected output: {expected_output}
Required tools: {required_tools}
Available tools schema: {tool_schemas}

Generate the exact ToolCall structure.
"""

class Planner:
    def __init__(self, llm_client: LLMClient):
        self.llm = llm_client

    def create_plan(self, goal: str) -> Plan:
        """Decompose a high-level goal into a validated Pydantic Plan."""
        logger.info(f"Creating plan for goal: {goal}")
        prompt = PLANNER_PROMPT.format(goal=goal)
        try:
            plan = self.llm.generate_structured_output(prompt, Plan)
            logger.info(f"Successfully generated plan with {len(plan.tasks)} tasks.")
            return plan
        except ValidationError as e:
            logger.error(f"Failed to validate the plan schema generated by the LLM. Validation Error: {e}")
            raise ValueError(f"LLM produced an invalid plan structure: {e}") from e
        except Exception as e:
            logger.error(f"Planner failed: {e}")
            raise
            
    def generate_tool_call(self, task: Task, available_schemas: list) -> ToolCall:
        logger.info(f"Generating tool call for task: {task.task_id}")
        prompt = TOOL_CALL_PROMPT.format(
            task_description=task.description,
            expected_output=task.expected_output,
            required_tools=task.required_tools,
            tool_schemas=json.dumps(available_schemas)
        )
        try:
            return self.llm.generate_structured_output(prompt, ToolCall)
        except Exception as e:
            logger.error(f"Tool call generation failed: {e}")
            raise ValueError(f"Failed to generate tool call for task {task.task_id}: {e}") from e
